//! Every rule this binary knows about: the ones built into ZLint plus any
//! custom rules registered by the consuming build.
//!
//! The `custom_rules` module is generated by `build.zig` from the
//! `-Dcustom_rules` paths. When none are given it is an empty namespace, so
//! `all` degrades to just the builtin rules.

const std = @import("std");
const builtin_rules = @import("builtin_rules.zig");
const custom_rules = @import("custom_rules").custom_rules;

const builtin_decls = @typeInfo(builtin_rules).@"struct".decls;
const custom_decls = @typeInfo(custom_rules).@"struct".decls;

/// Rule implementation types, builtins first.
pub const all: []const type = blk: {
    var rules: [builtin_decls.len + custom_decls.len]type = undefined;
    for (builtin_decls, 0..) |decl, i| {
        rules[i] = validate(@field(builtin_rules, decl.name), "Builtin", decl.name);
    }
    for (custom_decls, builtin_decls.len..) |decl, i| {
        rules[i] = validate(@field(custom_rules, decl.name), "Custom", decl.name);
    }
    const frozen = rules;
    break :blk &frozen;
};

/// Rule names are kebab-case, but they're used as struct field names in
/// `RulesConfig.Rules`, which are snake_case.
pub fn snakeName(comptime RuleImpl: type) [:0]const u8 {
    comptime {
        @setEvalBranchQuota(10_000);
        var name: [RuleImpl.meta.name.len]u8 = undefined;
        @memcpy(&name, RuleImpl.meta.name);
        std.mem.replaceScalar(u8, &name, '-', '_');
        const frozen = name;
        return std.fmt.comptimePrint("{s}", .{&frozen});
    }
}

fn validate(comptime RuleImpl: type, comptime kind: []const u8, comptime decl_name: []const u8) type {
    if (!@hasDecl(RuleImpl, "meta")) {
        @compileError(kind ++ " rule '" ++ decl_name ++ "' is missing a `pub const meta: Rule.Meta` declaration.");
    }
    if (!@hasDecl(RuleImpl, "rule")) {
        @compileError(kind ++ " rule '" ++ decl_name ++ "' is missing a `pub fn rule(*@This()) Rule` method.");
    }
    return RuleImpl;
}
